export enum ErrorMessage {
	unexpected_error = "Unexpected error",
	user_already_exists = "User already exists",
	user_does_not_exist = "User does not exist",
	password_incorrect = "Password is incorrect",
	wrong_uuid = "Wrong uuid",
	delete_error = "Delete error",
	session_invalid = "Session is not valid",
	session_does_not_exist = "Session does not exist",
	session_inactive = "Session is not active",
	playlist_already_exists = "Playlist already exists",
	playlist_does_not_exist = "Playlist does not exist",
	song_does_not_exist = "Song does not exist",
	could_not_load_file = "Could not load file",
	could_not_upload_file = "Could not upload file",
	could_not_add_to_playlist = "Could not add to playlist",
}
